export let sources = [{
    title: "Lamkos",
    category:"text",
    descr: {
      size: "",
      duration: "",
      format: "",
    },
    downLink: "/mp4/lamkos.mp4",
    // videoPreview:"/mp4/lamkos-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722436/animated%20backgrounds/openR-thumbs/lamkos-s_r910g1.mp4",
    downloadFree: false,
    seamless: false,
  },
  {
    title: "polyconnect",
    category:"abstract",
    descr: {
      size: "1920X1080 (1.08mb) ",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/polyconnect.mp4",
    // videoPreview:"/mp4/polyconnect-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722437/animated%20backgrounds/openR-thumbs/polyconnect-s_tomay6.mp4",

    downloadFree: true,
    seamless: true,
  },
  {

    title: "electrons",
    category:"text",
    descr: {
      size: "",
      duration: "",
      format: "",
    },
    downLink: "/mp4/electrons.mp4",
    // videoPreview:"/mp4/electrons-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722438/animated%20backgrounds/openR-thumbs/electrons-s_o94geh.mp4",

    downloadFree: false,
    seamless: false,
  },
  {

    title: "connect1",
    category:"abstract",
    descr: {
      size: "1920X1080 (1.03mb) ",
      duration: "3s",
      format: "25fps mp4",
    },
    downLink: "/mp4/connect1.mp4",
    // videoPreview:"/mp4/connect1-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722443/animated%20backgrounds/openR-thumbs/connect1-s_jbxgq2.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "jeskai-ink",
    category:"text",
    descr: {
      size: "4:055s 30fps mp4",
      duration: "",
      format: "",
    },
    downLink: "/mp4/jeskai768.mp4",
    // videoPreview:"/mp4/jeskai-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722437/animated%20backgrounds/openR-thumbs/jeskai-s_qyf2xv.mp4",
    downloadFree: false,
    seamless: false,
  },

  {

    title: "wavy-blobs",
    category:"abstract",
    descr: {
      size: "1920X1080 (0.35mb) ",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/wavy-blobs.mp4",
    // videoPreview:"/mp4/wavy-blobs-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722439/animated%20backgrounds/openR-thumbs/wavy-blobs-s_n3j0f7.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Constellation",
    category:"abstract",
    descr: {
      size: "1080x1920 (0.7mb) ",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/constell.mp4",
    // videoPreview:"/mp4/constell-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722440/animated%20backgrounds/openR-thumbs/constell-s_ymcfnk.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Bokeh-green",
    category:"abstract",
    descr: {
      size: "1080x1920 (0.85mb) ",
      duration: "5s",
      format: "25fps mp4",
    },
    downLink: "/mp4/bokeh-green.mp4",
    // videoPreview:"/mp4/bokeh-green-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722436/animated%20backgrounds/openR-thumbs/bokeh-green-s_bdhggz.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Bokeh-red",
    category:"abstract",
    descr: {
      size: "1080x1920 (0.7mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/bokeh-red.mp4",
    // videoPreview:"/mp4/bokeh-red-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722435/animated%20backgrounds/openR-thumbs/bokeh-red-s_pufxsr.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "PsycSplash",
    category:"abstract",
    descr: {
      size: "1080x1920 (2.13mb)",
      duration: "10s",
      format: "25fps mp4",
    },
    downLink: "/mp4/psychSplash.mp4",

    // videoPreview:"/mp4/psychSplash-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603718323/animated%20backgrounds/openR-thumbs/psychSplash-s_qspklj.mp4",

    downloadFree: true,
    seamless: true,
  },
  {
    title: "Oceanic",
    category:"text",
    descr: {
      size: "1080x1920 (1.7mb)",
      duration: "5s",
      format: "25fps mp4",
    },
    downLink: "/mp4/oceanic.mp4",
    // videoPreview:"/mp4/oceanic-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722822/animated%20backgrounds/openR-thumbs/oceanic-s_xnkuay.mp4",
    downloadFree: false,
    seamless: false,
  },
  {
    title: "Glitchy",
    category:"text",
    descr: {
      size: "",
      duration: "",
    },
    downLink: "/mp4/glitchy.mp4",
    // videoPreview:"/mp4/glitchy-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722435/animated%20backgrounds/openR-thumbs/glitchy-s_n2gcwq.mp4",
    downloadFree: false,
    seamless: true,
  },
  {
    title: "Cubic",
    category:"text",
    descr: {
      size: "",
      duration: "",
      format: "",
    },
    downLink: "/mp4/cubic.mp4",
    // videoPreview:"/mp4/cubic-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722443/animated%20backgrounds/openR-thumbs/cubic-s_pculmj.mp4",
    downloadFree: false,
    seamless: false,
  },
  {
    title: "Countdown",
    category:"counters",
    descr: {
      size: "1080x1920 (0.4mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/countdown.mp4",
    // videoPreview:"/mp4/countdown-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722437/animated%20backgrounds/openR-thumbs/countdown-s_tonezi.mp4",
    downloadFree: true,
    seamless: false,
  },
  {
    title: "Hey",
    category:"text",
    descr: {
      size: "1080x1920 (0.4mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/hey.mp4",
    // videoPreview:"/mp4/hey-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722445/animated%20backgrounds/openR-thumbs/hey-s_nujxn3.mp4",
    downloadFree: false,
    seamless: false,
  },
  {
    title: "Countdown2",
    category:"counters",
    descr: {
      size: "1080x1920 (0.7mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/countdown.mp4",
    // videoPreview:"/mp4/countdown2-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722442/animated%20backgrounds/openR-thumbs/countdown2-s_fbaxgz.mp4",
    downloadFree: true,
    seamless: false,
  },
  {
    title: "Stream",
    category:"stream",
    descr: {
      size: "1080x1920 (0.6mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/streamStarts.mp4",
    // videoPreview:"/mp4/streamStarts-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722434/animated%20backgrounds/openR-thumbs/streamStarts-s_ng9uqa.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
        title: "Stream2",
    category:"stream",
    descr: {
      size: "1080x1920 (4.5mb)",
      duration: "7s",
      format: "25fps mp4",
    },
    downLink: "/mp4/streamStarts2.mp4",
    // videoPreview:"/mp4/streamStarts2-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603723076/animated%20backgrounds/openR-thumbs/streamStarts2-s_elbyan.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Blobsun",
    category:"abstract",
    descr: {
      size: "1080x1920 (0.5mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/blobsun.mp4",
    // videoPreview:"/mp4/blobsun-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722434/animated%20backgrounds/openR-thumbs/blobsun-s_xmicjp.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Interact",
    category:"text",
    descr: {
      size: "1080x1920 (2.7mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/interact.mp4",
    // videoPreview:"/mp4/interact-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722446/animated%20backgrounds/openR-thumbs/interact-s_l0t7dv.mp4",
    downloadFree: false,
    seamless: false,
  },
  {
    title: "Stream3",
    category:"stream",
    descr: {
      size: "1080x1920 (5mb)",
      duration: "7s",
      format: "25fps mp4",
    },
    downLink: "/mp4/streamStarts3.mp4",
    // videoPreview:"/mp4/streamStarts3-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603723192/animated%20backgrounds/openR-thumbs/streamStarts3-s_cghnif.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Simple Count",
    category:"counters",
    descr: {
      size: "1080x1920 (0.2mb)",
      duration: "5s",
      format: "25fps mp4",
    },
    downLink: "/mp4/simpleCount.mp4",
    // videoPreview:"/mp4/streamStarts3-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1605615648/animated%20backgrounds/openR-thumbs/simpleCount-s_bokrs3.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Stream-shaky",
    category:"stream",
    descr: {
      size: "1080x1920 (7mb)",
      duration: "7s",
      format: "25fps mp4",
    },
    downLink: "/mp4/streamStarts4-shakey.mp4",
    // videoPreview:"/mp4/streamStarts-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1605799584/animated%20backgrounds/openR-thumbs/streamStarts4-shakey-s_xhcnym.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Stream-play",
    category:"stream",
    descr: {
      size: "1080x1920 (0.85mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/streamStarts5_play.mp4",
    // videoPreview:"/mp4/streamStarts-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1605968339/animated%20backgrounds/openR-thumbs/streamStarts5_play-s_lkh1mp.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Clock-hip",
    category:"counters",
    descr: {
      size: "1080x1920 (1.5mb)",
      duration: "10s",
      format: "25fps mp4",
    },
    downLink: "/mp4/clock-hip.mp4",
    // videoPreview:"/mp4/streamStarts3-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1605964145/animated%20backgrounds/openR-thumbs/clock-hip-s_n70ski.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Stream-hover",
    category:"stream",
    descr: {
      size: "1080x1920 (0.5mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/streamStarts6_hover.mp4",
    // videoPreview:"/mp4/streamStarts-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1606312602/animated%20backgrounds/openR-thumbs/streamStarts6_hover-s_r3flwx.mp4",
    downloadFree: true,
    seamless: true,
  },

];

// console.log(sources.length)