export let sources = [
  {
    title: "Polyconnect",
    category:["abstract","featured"],
    descr: {
      size: "1920X1080 (1.08mb) ",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/polyconnect.mp4",
    // videoPreview:"/mp4/polyconnect-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722437/animated%20backgrounds/openR-thumbs/polyconnect-s_tomay6.mp4",

    downloadFree: true,
    seamless: true,
  },
  {

    title: "Electrons",
    category:["text",],
    descr: {
      size: "",
      duration: "",
      format: "",
    },
    downLink: "/mp4/electrons.mp4",
    // videoPreview:"/mp4/electrons-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1623942234/animated%20backgrounds/openR-thumbs/streamStarts-blink-s_wbvfev.mp4",

    downloadFree: false,
    seamless: false,
  },
  {

    title: "Connect1",
    category:["abstract",],
    descr: {
      size: "1920X1080 (1.03mb) ",
      duration: "3s",
      format: "25fps mp4",
    },
    downLink: "/mp4/connect1.mp4",
    // videoPreview:"/mp4/connect1-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722443/animated%20backgrounds/openR-thumbs/connect1-s_jbxgq2.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Lamkos",
    category:["text","featured"],
    descr: {
      size: "",
      duration: "",
      format: "",
    },
    downLink: "/mp4/lamkos.mp4",
    // videoPreview:"/mp4/lamkos-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722436/animated%20backgrounds/openR-thumbs/lamkos-s_r910g1.mp4",
    downloadFree: false,
    seamless: false,
  },
  {
    title: "Jeskai-ink",
    category:["text","featured"],
    descr: {
      size: "4:055s 30fps mp4",
      duration: "",
      format: "",
    },
    downLink: "/mp4/jeskai768.mp4",
    // videoPreview:"/mp4/jeskai-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722437/animated%20backgrounds/openR-thumbs/jeskai-s_qyf2xv.mp4",
    downloadFree: false,
    seamless: false,
  },

  {

    title: "Wavy-blobs",
    category:["abstract",],
    descr: {
      size: "1920X1080 (0.35mb) ",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/wavy-blobs.mp4",
    // videoPreview:"/mp4/wavy-blobs-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1610132939/animated%20backgrounds/openR-thumbs/wavy-blobs-vs_f9tmkr.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Constellation",
    category:["abstract",],
    descr: {
      size: "1080x1920 (0.7mb) ",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/constell.mp4",
    // videoPreview:"/mp4/constell-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722440/animated%20backgrounds/openR-thumbs/constell-s_ymcfnk.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Bokeh-green",
    category:["abstract","featured"],
    descr: {
      size: "1080x1920 (0.85mb) ",
      duration: "5s",
      format: "25fps mp4",
    },
    downLink: "/mp4/bokeh-green.mp4",
    // videoPreview:"/mp4/bokeh-green-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722436/animated%20backgrounds/openR-thumbs/bokeh-green-s_bdhggz.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Bokeh-red",
    category:["abstract",],
    descr: {
      size: "1080x1920 (0.7mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/bokeh-red.mp4",
    // videoPreview:"/mp4/bokeh-red-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722435/animated%20backgrounds/openR-thumbs/bokeh-red-s_pufxsr.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "PsycSplash",
    category:["abstract",],
    descr: {
      size: "1080x1920 (2.13mb)",
      duration: "10s",
      format: "25fps mp4",
    },
    downLink: "/mp4/psychSplash.mp4",

    // videoPreview:"/mp4/psychSplash-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603718323/animated%20backgrounds/openR-thumbs/psychSplash-s_qspklj.mp4",

    downloadFree: true,
    seamless: true,
  },
  {
    title: "Oceanic",
    category:["text",],
    descr: {
      size: "1080x1920 (1.7mb)",
      duration: "5s",
      format: "25fps mp4",
    },
    downLink: "/mp4/oceanic.mp4",
    // videoPreview:"/mp4/oceanic-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722822/animated%20backgrounds/openR-thumbs/oceanic-s_xnkuay.mp4",
    downloadFree: false,
    seamless: false,
  },
  {
    title: "Glitchy",
    category:["text",],
    descr: {
      size: "",
      duration: "",
    },
    downLink: "/mp4/glitchy.mp4",
    // videoPreview:"/mp4/glitchy-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722435/animated%20backgrounds/openR-thumbs/glitchy-s_n2gcwq.mp4",
    downloadFree: false,
    seamless: true,
  },
  {
    title: "Cubic",
    category:["text","featured"],
    descr: {
      size: "",
      duration: "",
      format: "",
    },
    downLink: "/mp4/cubic.mp4",
    // videoPreview:"/mp4/cubic-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722443/animated%20backgrounds/openR-thumbs/cubic-s_pculmj.mp4",
    downloadFree: false,
    seamless: false,
  },
  {
    title: "Countdown",
    category:["counters",],
    descr: {
      size: "1080x1920 (0.4mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/countdown.mp4",
    // videoPreview:"/mp4/countdown-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722437/animated%20backgrounds/openR-thumbs/countdown-s_tonezi.mp4",
    downloadFree: true,
    seamless: false,
  },
  {
    title: "Hey",
    category:["text",],
    descr: {
      size: "1080x1920 (0.4mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/hey.mp4",
    // videoPreview:"/mp4/hey-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722445/animated%20backgrounds/openR-thumbs/hey-s_nujxn3.mp4",
    downloadFree: false,
    seamless: false,
  },
  {
    title: "Countdown2",
    category:["counters","featured"],
    descr: {
      size: "1080x1920 (0.7mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/countdown.mp4",
    // videoPreview:"/mp4/countdown2-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722442/animated%20backgrounds/openR-thumbs/countdown2-s_fbaxgz.mp4",
    downloadFree: true,
    seamless: false,
  },
  {
    title: "Stream",
    category:["stream","featured"],
    descr: {
      size: "1080x1920 (0.6mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/streamStarts.mp4",
    // videoPreview:"/mp4/streamStarts-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722434/animated%20backgrounds/openR-thumbs/streamStarts-s_ng9uqa.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
        title: "Stream2",
    category:["stream",],
    descr: {
      size: "1080x1920 (4.5mb)",
      duration: "7s",
      format: "25fps mp4",
    },
    downLink: "/mp4/streamStarts2.mp4",
    // videoPreview:"/mp4/streamStarts2-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603723076/animated%20backgrounds/openR-thumbs/streamStarts2-s_elbyan.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Blobsun",
    category:["abstract",],
    descr: {
      size: "1080x1920 (0.5mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/blobsun.mp4",
    // videoPreview:"/mp4/blobsun-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722434/animated%20backgrounds/openR-thumbs/blobsun-s_xmicjp.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Interact",
    category:["text","featured"],
    descr: {
      size: "1080x1920 (2.7mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/interact.mp4",
    // videoPreview:"/mp4/interact-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603722446/animated%20backgrounds/openR-thumbs/interact-s_l0t7dv.mp4",
    downloadFree: false,
    seamless: false,
  },
  {
    title: "Stream3",
    category:["stream",],
    descr: {
      size: "1080x1920 (5mb)",
      duration: "7s",
      format: "25fps mp4",
    },
    downLink: "/mp4/streamStarts3.mp4",
    // videoPreview:"/mp4/streamStarts3-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1603723192/animated%20backgrounds/openR-thumbs/streamStarts3-s_cghnif.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Simple Count",
    category:["counters",],
    descr: {
      size: "1080x1920 (0.2mb)",
      duration: "5s",
      format: "25fps mp4",
    },
    downLink: "/mp4/simpleCount.mp4",
    // videoPreview:"/mp4/streamStarts3-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1605615648/animated%20backgrounds/openR-thumbs/simpleCount-s_bokrs3.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Stream-shaky",
    category:["stream",],
    descr: {
      size: "1080x1920 (7mb)",
      duration: "7s",
      format: "25fps mp4",
    },
    downLink: "/mp4/streamStarts4-shakey.mp4",
    // videoPreview:"/mp4/streamStarts-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1605799584/animated%20backgrounds/openR-thumbs/streamStarts4-shakey-s_xhcnym.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Stream-play",
    category:["stream","featured"],
    descr: {
      size: "1080x1920 (0.85mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/streamStarts5_play.mp4",
    // videoPreview:"/mp4/streamStarts-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1605968339/animated%20backgrounds/openR-thumbs/streamStarts5_play-s_lkh1mp.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Clock-hip",
    category:["counters",],
    descr: {
      size: "1080x1920 (1.5mb)",
      duration: "10s",
      format: "25fps mp4",
    },
    downLink: "/mp4/clock-hip.mp4",
    // videoPreview:"/mp4/streamStarts3-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1605964145/animated%20backgrounds/openR-thumbs/clock-hip-s_n70ski.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Stream-hover",
    category:["stream","featured"],
    descr: {
      size: "1080x1920 (0.5mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/streamStarts6_hover.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1606312602/animated%20backgrounds/openR-thumbs/streamStarts6_hover-s_r3flwx.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Number1",
    category:["counters",],
    descr: {
      size: "1080x1920 (0.45mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/num_1_sptn.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1606831568/animated%20backgrounds/openR-thumbs/num_1_sptn-s_s28ww6.mp4",
    downloadFree: true,
    seamless: false,
  },
  {
    title: "Number2",
    category:["counters",],
    descr: {
      size: "1080x1920 (0.45mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/num_2_sptn.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1606831567/animated%20backgrounds/openR-thumbs/num_2_sptn-s_niobz6.mp4",
    downloadFree: true,
    seamless: false,
  },
  {
    title: "Number3",
    category:["counters",],
    descr: {
      size: "1080x1920 (0.45mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/num_3_sptn.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1606831565/animated%20backgrounds/openR-thumbs/num_3_sptn-s_dmjd5e.mp4",
    downloadFree: true,
    seamless: false,
  },
  {
    title: "Particles-round",
    category:["particles",],
    descr: {
      size: "1080x1920 (0.55mb)",
      duration: "6s",
      format: "25fps mp4",
    },
    downLink: "/mp4/particles-round.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1606936029/animated%20backgrounds/openR-thumbs/particles-round-s_xqns4j.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Particles-fireflies",
    category:["particles",],
    descr: {
      size: "1080x1920 (1.55mb)",
      duration: "7s",
      format: "25fps mp4",
    },
    downLink: "/mp4/particles-fireflies.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1607026650/animated%20backgrounds/openR-thumbs/particles-fireflies-s_trmuqy.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Particles-soap",
    category:["particles","text"],
    descr: {
      size: "1080x1920 (0.55mb)",
      duration: "7s",
      format: "25fps mp4",
    },
    downLink: "/mp4/particles-soap.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1607085150/animated%20backgrounds/openR-thumbs/particles-soap-s_pdwttl.mp4",
    downloadFree: false,
    seamless: true,
  },
  {
    title: "Particles-love",
    category:["particles","text"],
    descr: {
      size: "1080x1920 (1.2mb)",
      duration: "7s",
      format: "25fps mp4",
    },
    downLink: "/mp4/particles-love.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1607619520/animated%20backgrounds/openR-thumbs/particles-love-s_tdcgfn.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Particles-expanse",
    category:["particles","abstract"],
    descr: {
      size: "1080x1920 (1.6mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/particles-expanse.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1607351523/animated%20backgrounds/openR-thumbs/particles-expanse-s_gf7p7e.mp4",
    downloadFree: true,
    seamless: false,
  },
  {
    title: "Particles-love2",
    category:["particles","text","featured"],
    descr: {
      size: "1080x1920 (2.65mb)",
      duration: "7s",
      format: "25fps mp4",
    },
    downLink: "/mp4/particles-love2.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1607620346/animated%20backgrounds/openR-thumbs/particles-love2-s_u60rcu.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Particles-pixels",
    category:["particles","text"],
    descr: {
      size: "1080x1920 (1mb)",
      duration: "5s",
      format: "25fps mp4",
    },
    downLink: "/mp4/particles-pixels.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1607698977/animated%20backgrounds/openR-thumbs/particles-pixels-s_odgoxu.mp4",
    downloadFree: false,
    seamless: false,
  },
  {
    title: "Double Helix",
    category:["particles","featured"],
    descr: {
      size: "1080x1920 (1.7mb)",
      duration: "3s",
      format: "25fps mp4",
    },
    downLink: "/mp4/Double-helix.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1609501042/animated%20backgrounds/openR-thumbs/DoubleHelix-vs_ojmpxt.mp4",
    downloadFree: true,
    seamless: false,
  },
  {
    title: "Molecular Soup",
    category:["abstract"],
    descr: {
      size: "1080x1920 (2.45mb)",
      duration: "5s",
      format: "25fps mp4",
    },
    downLink: "/mp4/molsoup.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1608148653/animated%20backgrounds/openR-thumbs/molsoup-s_xfbprb.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Elastic",
    category:["text","featured"],
    descr: {
      size: "1080x1920 (0.65mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/elastic.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1608484000/animated%20backgrounds/openR-thumbs/elastic-s_nokxmn.mp4",
    downloadFree: false,
    seamless: false,
  },
  {
    title: "Warp",
    category:["text",],
    descr: {
      size: "1080x1920 (0.3mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/warp.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1608577385/animated%20backgrounds/openR-thumbs/warp-s_znlw66.mp4",
    downloadFree: false,
    seamless: false,
  },
  {
    title: "Number3-rays",
    category:["counters",],
    descr: {
      size: "1080x1920 (0.3mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/num_3_rays.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1608731648/animated%20backgrounds/openR-thumbs/num_3_rays-s_pevmec.mp4",
    downloadFree: true,
    seamless: false,
  },
  {
    title: "Number2-rays",
    category:["counters",],
    descr: {
      size: "1080x1920 (0.3mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/num_2_rays.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1608740857/animated%20backgrounds/openR-thumbs/num_2_rays-s_m2ooo4.mp4",
    downloadFree: true,
    seamless: false,
  },
  {
    title: "Number1-rays",
    category:["counters",],
    descr: {
      size: "1080x1920 (0.25mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/num_1_rays.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1608740858/animated%20backgrounds/openR-thumbs/num_1_rays-s_i1x0tz.mp4",
    downloadFree: true,
    seamless: false,
  },
  {
    title: "Letters-hover",
    category:["text",],
    descr: {
      size: "1080x1920 (0.1mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/letters1.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1608919829/animated%20backgrounds/openR-thumbs/letters1_-_s_djfqov.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Letters-hover2",
    category:["text",],
    descr: {
      size: "1080x1920 (0.1mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/letters2.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1608919830/animated%20backgrounds/openR-thumbs/letters2_-_s_a0k0gk.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Lines",
    category:["abstract",],
    descr: {
      size: "1080x1920 (0.1mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/lines-bg.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1608919829/animated%20backgrounds/openR-thumbs/lines-bg_-_s_beg8xs.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "FUI",
    category:["text","featured"],
    descr: {
      size: "1080x1920 (1.55mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/fui.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1608994434/animated%20backgrounds/openR-thumbs/fui-s_ftxrw4.mp4",
    downloadFree: true,
    seamless: false,
  },
  {
    title: "Sea",
    category:["abstract",],
    descr: {
      size: "1080x1920 (2.5mb)",
      duration: "10s",
      format: "25fps mp4",
    },
    downLink: "/mp4/sea.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1609235393/animated%20backgrounds/openR-thumbs/sea-vs_dyoutg.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Blob-num1",
    category:["abstract","text","counters"],
    descr: {
      size: "1080x1920 (0.45mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/wavy-blobs-num1.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1609353165/animated%20backgrounds/openR-thumbs/wavy-blobs-num1-vs_qvopgi.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Pebbles",
    category:["text","particles"],
    descr: {
      size: "1080x1920 (0.5mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/pebbles.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1609865872/animated%20backgrounds/openR-thumbs/pebbles-s_qkoobu.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Sun",
    category:["particles"],
    descr: {
      size: "1080x1920 (2.2mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/particles-sun.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1610379470/animated%20backgrounds/openR-thumbs/particles-sun-s_uw6yem.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "We like cubes",
    category:["text",],
    descr: {
      size: "1080x1920 (0.4mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/hey.mp4",
    // videoPreview:"/mp4/hey-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1610538124/animated%20backgrounds/openR-thumbs/likecubes-s_q5camq.mp4",
    downloadFree: false,
    seamless: false,
  },
  {
    title: "Overthinking",
    category:["text","featured"],
    descr: {
      size: "1080x1920 (1.5mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/overthinking.mp4",
    // videoPreview:"/mp4/hey-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1610966458/animated%20backgrounds/openR-thumbs/overthinking-vs_jmhsps.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "BLM",
    category:["text"],
    descr: {
      size: "1080x1920 (3.15mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/BLM.mp4",
    // videoPreview:"/mp4/hey-s.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1611511080/animated%20backgrounds/openR-thumbs/BLM-vs_lvkzg0.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Nice Hair",
    category:["text"],
    descr: {
      size: "1080x1920 (3.15mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1611511081/animated%20backgrounds/openR-thumbs/nice-hair_g-vs_veisco.mp4",
    downloadFree: false,
    seamless: true,
  },
  {
    title: "Data Flow",
    category:["text","featured"],
    descr: {
      size: "",
      duration: "",
      format: "",
    },
    downLink: "",
       videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1611760542/animated%20backgrounds/openR-thumbs/dataflow-vs_z8qwht.mp4",
    downloadFree: false,
    seamless: false,
  },
  {
    title: "Stream-StartingSoon",
    category:["stream","featured"],
    descr: {
      size: "1080x1920 (1.65mb)",
      duration: "5s",
      format: "25fps mp4",
    },
    downLink: "/mp4/streamStarts-still.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1612540740/animated%20backgrounds/openR-thumbs/streamStarts-still-vs_q7pbpg.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Stream-MTG",
    category:["stream","featured"],
    descr: {
      size: "1080x1920 (0.5mb)",
      duration: "3s",
      format: "25fps mp4",
    },
    downLink: "/mp4/streamStarts-still.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1612978839/animated%20backgrounds/openR-thumbs/streamStarts-MTG-vs_hcbf0q.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Threads",
    category:["text","particles"],
    descr: {
      size: "",
      duration: "5s",
      format: "25fps mp4",
    },
    downLink: "",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1613311009/animated%20backgrounds/openR-thumbs/threads-s_uzggyn.mp4",
    downloadFree: false,
    seamless: false,
  },
  {
    title: "Transition-circles",
    category:["featured","transitions"],
    descr: {
      size: "0.25mb",
      duration: "2s",
      format: "25fps mp4",
    },
    downLink: "/mp4/transition-circles.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1615309349/animated%20backgrounds/openR-thumbs/transition-circles-s_jewsm5.mp4",
    downloadFree: true,
    seamless: false,
  },
  {
    title: "StreamIn5",
    category:["stream","featured"],
    descr: {
      size: "1080x1920 (0.5mb)",
      duration: "6s",
      format: "25fps mp4",
    },
    downLink: "/mp4/streamIn5.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1615397126/animated%20backgrounds/openR-thumbs/streamIn5-vs_qb5p4z.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Stream-going live",
    category:["stream"],
    descr: {
      size: "1080x1920 (0.8mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/goinlive.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1615904254/animated%20backgrounds/openR-thumbs/goinlive-s_rg7o5t.mp4",
    downloadFree: true,
    seamless: true,
  },
  {
    title: "Transition-curtain",
    category:["featured","transitions"],
    descr: {
      size: "0.1mb",
      duration: "3s",
      format: "25fps mp4",
    },
    downLink: "/mp4/transition_curtains.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1621418533/animated%20backgrounds/openR-thumbs/transition_curtains_s_liwxxe.mp4",
    downloadFree: true,
    seamless: false,
  },
  {
    title: "Transition-grid",
    category:["transitions",'featured'],
    descr: {
      size: "0.3mb",
      duration: "2s",
      format: "25fps mp4",
    },
    downLink: "/mp4/transition-grid.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1621704419/animated%20backgrounds/openR-thumbs/transition-grid-s_ty1wko.mp4",
    downloadFree: true,
    seamless: false,
  },
  {
    title: "Transition-wave",
    category:["transitions"],
    descr: {
      size: "0.25mb",
      duration: "2s",
      format: "25fps mp4",
    },
    downLink: "/mp4/transition_wave.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1622626322/animated%20backgrounds/openR-thumbs/transition_wave-s_me8n8a.mp4",
    downloadFree: true,
    seamless: false,
  },
  {
    title: "Transition-stars",
    category:["featured","transitions"],
    descr: {
      size: "0.36mb",
      duration: "2s",
      format: "25fps mp4",
    },
    downLink: "/mp4/transition_stars.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1623150388/animated%20backgrounds/openR-thumbs/transition_stars-s_bw9xu6.mp4",
    downloadFree: true,
    seamless: false,
  },
  {
    title: "Transition-split",
    category:["transitions"],
    descr: {
      size: "0.2mb",
      duration: "2s",
      format: "25fps mp4",
    },
    downLink: "/mp4/trans-split.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1623394524/animated%20backgrounds/openR-thumbs/trans-split-s_dobjwz.mp4",
    downloadFree: true,
    seamless: false,
  },
  {
    title: "Transition-shutter",
    category:["featured","transitions"],
    descr: {
      size: "0.28mb",
      duration: "2s",
      format: "25fps mp4",
    },
    downLink: "/mp4/transition_shutter.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1623745831/animated%20backgrounds/openR-thumbs/transition_shutter-s_wlmnu8.mp4",
    downloadFree: true,
    seamless: false,
  },
  {
    title: "Stream-blinky letters",
    category:["stream","featured"],
    descr: {
      size: "1080x1920 (0.3mb)",
      duration: "4s",
      format: "25fps mp4",
    },
    downLink: "/mp4/streamStarts-blink.mp4",
    videoPreview:"https://res.cloudinary.com/lamkos/video/upload/v1623942234/animated%20backgrounds/openR-thumbs/streamStarts-blink-s_wbvfev.mp4",
    downloadFree: true,
    seamless: true,
  },
  

];

// console.log(sources.length)
